### ISSUE TITLE
Check strange error in apisearch_server in docker

### ISSUE THREAD

**Issue by mmoreram** [apisearch-io/search-server#44]
```
apisearch_server | 2018-05-29 14:41:46,879 INFO exited: search-server-4 (exit status 255; not expected)
apisearch_server | Traceback (most recent call last):
apisearch_server |   File "/usr/bin/supervisord", line 9, in <module>
apisearch_server |     load_entry_point('supervisor==3.0', 'console_scripts', 'supervisord')()
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 360, in main
apisearch_server |     go(options)
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 370, in go
apisearch_server |     d.main()
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 83, in main
apisearch_server |     self.run()
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 100, in run
apisearch_server |     self.runforever()
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 252, in runforever
apisearch_server |     [ group.transition() for group  in pgroups ]
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 697, in transition
apisearch_server |     proc.transition()
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 533, in transition
apisearch_server |     self.spawn()
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/process.py", line 219, in spawn
apisearch_server |     self.dispatchers, self.pipes = self.config.make_dispatchers(self)
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1683, in make_dispatchers
apisearch_server |     dispatchers[stdout_fd] = POutputDispatcher(proc, etype, stdout_fd)
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/dispatchers.py", line 98, in __init__
apisearch_server |     backups=backups)
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 446, in getLogger
apisearch_server |     backups, stdout)
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 344, in getLogger
apisearch_server |     handlers.append(RotatingFileHandler(filename,'a',maxbytes,backups))
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 172, in __init__
apisearch_server |     FileHandler.__init__(self, filename, mode)
apisearch_server |   File "/usr/lib/python2.7/dist-packages/supervisor/loggers.py", line 98, in __init__
apisearch_server |     self.stream = open(filename, mode)
apisearch_server | IOError: [Errno 2] No such file or directory: '/var/log/supervisor/search-server-4.log'
apisearch_server exited with code 1
```

**Comment by mmoreram** [comment]
Seems related to the supervisord logs file. Never seen again. Added in the historical backlog of Server issues.
